name: DevOps

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Ejecutar un script simple
        run: echo "Prueba, CI"

      - name: Ejecutar un script multi-línea
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."